export const LOADING_ACTION = 'LOADING_ACTION';

export const GET_ALL_TODOS_REQUESTED = 'GET_ALL_TODOS_REQUESTED';
export const GET_ALL_TODOS_SUCCEEDED = 'GET_ALL_TODOS_SUCCEEDED';
export const GET_ALL_TODOS_FAILED = 'GET_ALL_TODOS_FAILED';
export const GET_ALL_TODOS_FAILED_TOKEN = 'GET_ALL_TODOS_FAILED_TOKEN';

export const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED';
export const DELETE_TODO_SUCCEEDED = 'DELETE_TODO_SUCCEEDED';
export const DELETE_TODO_FAILED = 'DELETE_TODO_FAILED';

export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const ADD_TODO_SUCCEEDED = 'ADD_TODO_SUCCEEDED';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const UPDATE_TODO_REQUESTED = 'UPDATE_TODO_REQUESTED';
export const UPDATE_TODO_SUCCEEDED = 'UPDATE_TODO_SUCCEEDED';
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';

export const EDIT_TODO_REQUESTED = 'EDIT_TODO_REQUESTED';
export const EDIT_TODO_SUCCEEDED = 'EDIT_TODO_SUCCEEDED';
export const EDIT_TODO_FAILED = 'EDIT_TODO_FAILED';

export const DELETE_ALL_TODO_REQUESTED = 'DELETE_ALL_TODO_REQUESTED';
export const DELETE_ALL_TODO_SUCCEEDED = 'DELETE_ALL_TODO_SUCCEEDED';
export const DELETE_ALL_TODO_FAILED = 'DELETE_ALL_TODO_FAILED';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_RESET = 'REGISTER_RESET';

export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const RECORD_AUTO_LOGIN = 'RECORD_AUTO_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_RESET = 'LOGIN_RESET';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const SELECT_TODO_REQUESTED = 'SELECT_TODO_REQUESTED';

export const GET_USER_DETAILS_REQUESTED = 'GET_USER_DETAILS_REQUESTED';
export const GET_USER_DETAILS_SUCCEEDED = 'GET_USER_DETAILS_SUCCEEDED';
export const GET_USER_DETAILS_FAILED = 'GET_USER_DETAILS_FAILED';
// export const USER_DETAIL_RESET = 'USER_DETAIL_RESET';

export const GET_USERS_LIST_REQUESTED = 'GET_USERS_LIST_REQUESTED';
export const GET_USERS_LIST_SUCCEEDED = 'GET_USERS_LIST_SUCCEEDED';
export const GET_USERS_LIST_FAILED = 'GET_USERS_LIST_FAILED';

//change setting actions
export const CHANGE_PASSWORD_REQUESTED = 'CHANGE_PASSWORD_REQUESTED';
export const CHANGE_PASSWORD_SUCCEEDED = 'CHANGE_PASSWORD_SUCCEEDED';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET';

export const CHANGE_SEND_NOTIFICATION_REQUESTED = 'CHANGE_SEND_NOTIFICATION_REQUESTED';
export const CHANGE_SEND_NOTIFICATION_SUCCEEDED = 'CHANGE_SEND_NOTIFICATION_SUCCEEDED';
export const CHANGE_SEND_NOTIFICATION_FAILED = 'CHANGE_SEND_NOTIFICATION_FAILED';
export const CHANGE_SEND_NOTIFICATION_RESET = 'CHANGE_SEND_NOTIFICATION_RESET';

export const CHANGE_RECEIVE_NOTIFICATION_REQUESTED = 'CHANGE_RECEIVE_NOTIFICATION_REQUESTED';
export const CHANGE_RECEIVE_NOTIFICATION_SUCCEEDED = 'CHANGE_RECEIVE_NOTIFICATION_SUCCEEDED';
export const CHANGE_RECEIVE_NOTIFICATION_FAILED = 'CHANGE_RECEIVE_NOTIFICATION_FAILED';
export const CHANGE_RECEIVE_NOTIFICATION_RESET = 'CHANGE_RECEIVE_NOTIFICATION_RESET';

export const CHANGE_AVATAR_REQUESTED = 'CHANGE_AVATAR_REQUESTED';
export const CHANGE_AVATAR_SUCCEEDED = 'CHANGE_AVATAR_SUCCEEDED';
export const CHANGE_AVATAR_FAILED = 'CHANGE_AVATAR_FAILED';
export const CHANGE_AVATAR_RESET = 'CHANGE_AVATAR_RESET';

export const GET_ALL_SHOPPING_LISTS_REQUESTED = 'GET_ALL_SHOPPING_LISTS_REQUESTED';
export const GET_ALL_SHOPPING_LISTS_SUCCEEDED = 'GET_ALL_SHOPPING_LISTS_SUCCEEDED';
export const GET_ALL_SHOPPING_LISTS_FAILED = 'GET_ALL_SHOPPING_LISTS_FAILED';

export const ADD_SHOPPING_LIST_REQUESTED = 'ADD_SHOPPING_LIST_REQUESTED';
export const ADD_SHOPPING_LIST_SUCCEEDED = 'ADD_SHOPPING_LIST_SUCCEEDED';
export const ADD_SHOPPING_LIST_FAILED = 'ADD_SHOPPING_LIST_FAILED';

export const DELETE_SHOPPING_LIST_REQUESTED = 'DELETE_SHOPPING_LIST_REQUESTED';
export const DELETE_SHOPPING_LIST_SUCCEEDED = 'DELETE_SHOPPING_LIST_SUCCEEDED';
export const DELETE_SHOPPING_LIST_FAILED = 'DELETE_SHOPPING_LIST_FAILED';